### ISSUE TITLE
Why complex kernel config again?

### ISSUE THREAD

**Issue by Noxenious** [linux-sunxi/meta-sunxi#107]
Is it now ok to add kernel config options again? When I added the kernel recipe for 4.x I had a complex config with many options enabled which I removed again:

- ebutera - 
"please as @whirm said it's better to just use the sunxi_defconfig instead of adding those files, it's much easier to maintain"

If it´s ok, I´ll add back a few options myself.

**Comment by naguirre** [comment]
I preffer to use a complete defconfig as it's need anyway for modern DISTRO.
Most of embedded distro has systemd and udev, these days, so we need most of them.
If you like a smaller kernel footprint by using less options it's up to you to override this meta with a bbappend and include you own defconfig.

**Comment by ebutera** [comment]
i thought that the sunxi_defconfig had at least some of the most useful options enabled, but i was wrong.
However i was more against adding a defconfig for each board, not for enabling this or that option. Of course make a pull request if you want to add other useful options :)

**Comment by Noxenious** [comment]
Ok will add options that are useful along the way. Issue can be closed.
