### ISSUE TITLE
Yocto Project 2.0 Jethro

### ISSUE THREAD

**Issue by leon-anavi** [linux-sunxi/meta-sunxi#129]
Hi,

When do you plan to add a branch compatible with Yocto Project 2.0 Jethro?

Best regards, Leon

**Comment by naguirre** [comment]
As far as i know, master is compatible with Jethro.
At least i use it for more than 4 month now, without problem.

**Comment by leon-anavi** [comment]
Hi, thank you for the feedback. Using the master branch I have successfully built core-image-minimal for A10-OLinuXino-LIME. 

Anyway do you plan to create branch jethro? A branch with that name exists for some of the other BSP layers that I am using: meta-fsl-arm and meta-raspberrypi.

Thanks, Leon

**Comment by ebutera** [comment]
yes, a jethro branch will be created soon.

**Comment by leon-anavi** [comment]
OK, thank you. Looking forward to it. I will close the issue.
