### ISSUE TITLE
mainline 4.1 kernel (as long as 4.4) are broken regarding input devices

### ISSUE THREAD

**Issue by slapin** [linux-sunxi/meta-sunxi#131]
mainline 4.1 kernel (as long as 4.4) are broken regarding input devices as defconfig doesn't
contain CONFIG_INPUT_EVDEV which prevents /dev/input/eventX creation
as latest udev doesn't create device nodes and kernel doesn't pick up evdev (and keyboard + mouse are disabled too). dition of CONFIG_INPUT_EVDEV is enough to make X11/weston work with current
openembedded-core/systemd

**Comment by jlucius** [comment]
Created a pull request for new kernel versions. 4.4.3 and 4.5rc6.

Should that fix your problems?

**Comment by slapin** [comment]
if CONFIG_INPUT_EVDEV was added to defconfig, then I like this :)

**Comment by diegorondini** [comment]
I think this can be closed now:
`# zcat /proc/config.gz | grep CONFIG_INPUT_EVDEV
CONFIG_INPUT_EVDEV=y`
