### ISSUE TITLE
Support for orange-pi-zero

### ISSUE THREAD

**Issue by lbaudouin** [linux-sunxi/meta-sunxi#165]
The orange-pi-zero board (H2+) is not yet supported.

With the orange-pi-one conf, the board can't boot.
Did you plan to support this board ?

**Comment by ebutera** [comment]
i don't have the hardware to test it, and i don't know if it's supported in mainline kernel....i just see there is no dts for it in latest kernel so probably it is still not officially supported.
In sunxi wiki it says "H3 images are proven to run on H2+." but without hardware i can't say anything, maybe you just need to remove the missing features (gbit mac etc) from h3 dts.

**Comment by ebutera** [comment]
supported in master
