### ISSUE TITLE
No recipes available for /poky/meta-sunxi/recipes-graphics/tslib/tslib_1.1.bbappend

### ISSUE THREAD

**Issue by JOE-JOE-NGIGI** [linux-sunxi/meta-sunxi#173]
What does this mean?I'm using poky-morty.
Any help?

**Comment by twoerner** [comment]
A layer can extend a recipe (example.bb) from another layer by .bbapend'ing it (example.bbappend). However, if the base recipe (example.bb) goes away, bitbake will complain.

By default bitbake will error out in this situation. To get it to not error out but simply report and continue, add the following line to your local.conf:

    BB_DANGLINGAPPENDS_WARNONLY = "yes"

**Comment by JOE-JOE-NGIGI** [comment]
Thanks @twoerner .That worked

**Comment by ebutera** [comment]
i merged an old PR to disable it in morty and master, so you can just update to fix it.

But good to know there is a way to disable the error!
