### ISSUE TITLE
Dependency loop when using initramfs

### ISSUE THREAD

**Issue by agherzan** [linux-sunxi/meta-sunxi#178]
The current implementation inherits sdcard_image-sunxi.bbclass unconditionally which in turn, sets two depends on do_rootfs unconditionally again. 

```
do_rootfs[depends] += "virtual/kernel:do_deploy"                                                                                                                         
do_rootfs[depends] += "virtual/bootloader:do_deploy" 
```

This means that if I want to build an initramfs image in the kernel image I will get a dependency loop.

Can we change that by including these in IMAGE_DEPENDS_sunxi-sdimg?

```
IMAGE_DEPENDS_sunxi-sdimg += " \
                        parted-native \
                        mtools-native \
                        dosfstools-native \
                        virtual/kernel:do_deploy \
                        virtual/bootloader:do_deploy \
                        "
```

Any concerns against this change? Can we have it in morty too?

**Comment by ebutera** [comment]
yes it looks good to me, did you already test it?

**Comment by agherzan** [comment]
Haven't tested it in this specific case but we are using something similar in meta-raspberrrypi for a while without any issues.

**Comment by ebutera** [comment]
i've pushed the fix on master, i was running a test build on morty but it's taking forever so i'll push it later or if someone confirms it works.

**Comment by ebutera** [comment]
cherry-picked on morty too

**Comment by agherzan** [comment]
Thanks @ebutera . @shaunmulligan I know you've been testing this, could you please give the fix a try?
