### ISSUE TITLE
Consider using https://github.com/megous/linux/tree/orange-pi-4.12 as the kernel source

### ISSUE THREAD

**Issue by shaunmulligan** [linux-sunxi/meta-sunxi#187]
Has anyone considered using [Megous](https://github.com/megous/linux/tree/orange-pi-4.12) linux kernel in this BSP. It it kept pretty well up to date and includes a lot of useful patches on top of mainline that are useful to many of the Sunxi boards.  https://github.com/megous/linux/tree/orange-pi-4.12

**Comment by madscientist42** [comment]
Heh...  They're using 4.14, just for starters.  Most of what is there is **_supposed_** to be integrated into the mainline there.  Unless you're trying to use a NanoPI Neo2 or Neo2-Plus, there's a lot of the things supported there.  Right now, there's something with U-Boot keeping me from getting either of those up and running- and the support for 64-bits isn't quite Jelled in 4.12 unless they've got those parts in that kernel.

Could you offer observations on what actually is missing/not correct from this perspective...?

Certainly, if you feel like it'll do better, you can always add/extend some recipes from meta or meta-sunxi to build it as a preferred kernel for your chosen boards.
