### ISSUE TITLE
Release pyro branch

### ISSUE THREAD

**Issue by MicroJoe** [linux-sunxi/meta-sunxi#206]
In my current setup meta-sunxi is the only meta repository that is not supporting pyro. Please release such a branch so that we know that pyro is supported.

**Comment by ebutera** [comment]
actually there is already a pyro branch, usually we support only the latest version (rocko now) but of course i can pull patches if needed.

**Comment by MicroJoe** [comment]
My bad, I was meaning rocko. My eyes slipped and I did not see that there were a rocko branch too.
Thanks for providing this layer, currently poking it with mainline and Nanopi NEO. 👍
