### ISSUE TITLE
COPYING has been changed in Linux Mainline Kernel 

### ISSUE THREAD

**Issue by NguyenTrongThinh** [linux-sunxi/meta-sunxi#218]
The COPYING file now point to license file. It is not a license itself. so it will generate error while building. Please correct LICENSE in recipes kernel. 

This is the commit in mainline linux
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/COPYING?id=bf02d491237eea10290bd379bf7fc8c37ac6c3b4

**Comment by ebutera** [comment]
fixed in 6759ac4ce6e07a4a4e0cfb4d1b00c8a47905bec6
