### ISSUE TITLE
sumo branch

### ISSUE THREAD

**Issue by floion** [linux-sunxi/meta-sunxi#223]
Hi guys,
are you working on a sumo branch?

If not, could you create it off the current master please?

Thank you

**Comment by floion** [comment]
Maybe @ebutera ?

**Comment by floion** [comment]
Re-ping on this please?

**Comment by floion** [comment]
Or maybe @naguirre or @slapin ?

**Comment by naguirre** [comment]
i don't on my side, but PR are welcome :-)

**Comment by floion** [comment]
Thanks!
