### ISSUE TITLE
linux-sunxi 3.4

### ISSUE THREAD

**Issue by icapa** [linux-sunxi/meta-sunxi#231]
Hi!
I tried to compile sunxi kernel 3.4 using the configuration you proposed:

PREFERRED_PROVIDER_u-boot="u-boot-sunxi" 
PREFERRED_PROVIDER_virtual/bootloader="u-boot-sunxi" PREFERRED_PROVIDER_virtual/kernel="linux-sunxi"

I can't figure out what I'm doing wrong, I can't see any information in the output that gives me any clue about the problem, any idea please?

Thanks in advance, best regards!

This is the output
----------------------------
 In file included from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/kernel.h:20,
|                  from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/spinlock.h:55,
|                  from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/mmzone.h:7,
|                  from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/gfp.h:4,
|                  from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/slab.h:12,
|                  from /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/kernel/fork.c:14:
| /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/include/linux/log2.h:22:1: warning: ignoring attribute 'noreturn' because it conflicts with attribute 'const' [-Wattributes]
|  int ____ilog2_NaN(void);
|  ^~~
| /tmp/ccrNWAYb.s:
| /tmp/ccrNWAYb.s: Assembler messages:
| 
| Assembler messages:
| /tmp/ccrNWAYb.s:1093: Error: .err encountered
| 
| /tmp/ccrNWAYb.s:1093: Error: .err encountered
| /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/scripts/Makefile.build:307: recipe for target 'kernel/fork.o' failed
| make[3]: *** [kernel/fork.o] Error 1
| /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/Makefile:947: recipe for target 'kernel' failed
| make[2]: *** [kernel] Error 2
| 
| /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/scripts/Makefile.build:307: recipe for target 'kernel/fork.o' failed
| make[3]: *** [kernel/fork.o] Error 1
| /media/yocto/Olinuxino/poky/build/tmp/work-shared/olinuxino-a20/kernel-source/Makefile:947: recipe for target 'kernel' failed
| make[2]: *** [kernel] Error 2
| ERROR: oe_runmake failed
| Makefile:130: recipe for target 'sub-make' failed
| make[1]: *** [sub-make] Error 2
| Makefile:26: recipe for target 'all' failed
| make: *** [all] Error 2
| + die 'oe_runmake failed'
| + bbfatal_log 'oe_runmake failed'
| + '[' -p /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/fifo.5787 ']'
| + printf '%b\0' 'bbfatal_log oe_runmake failed'
| + exit 1
| + bb_exit_handler
| + ret=1
| + case $ret in
| + case $BASH_VERSION in
| + echo 'WARNING: /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/run.do_compile.5787:1 exit 1 from '\''exit 1'\'''
| WARNING: /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/run.do_compile.5787:1 exit 1 from 'exit 1'
| + exit 1
| 
| Makefile:130: recipe for target 'sub-make' failed
| make[1]: *** [sub-make] Error 2
| Makefile:26: recipe for target 'all' failed
| make: *** [all] Error 2
| + die 'oe_runmake failed'
| + bbfatal_log 'oe_runmake failed'
| + '[' -p /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/fifo.5787 ']'
| + printf '%b\0' 'bbfatal_log oe_runmake failed'
| + exit 1
| + bb_exit_handler
| + ret=1
| + case $ret in
| + case $BASH_VERSION in
| + echo 'WARNING: /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/run.do_compile.5787:1 exit 1 from '\''exit 1'\'''
| WARNING: /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/run.do_compile.5787:1 exit 1 from 'exit 1'
| + exit 1
| ERROR: Function failed: do_compile (log file is located at /media/yocto/Olinuxino/poky/build/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/log.do_compile.5787)
ERROR: Task (/media/yocto/Olinuxino/poky/meta-sunxi/recipes-kernel/linux/linux-sunxi_3.4.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 361 tasks of which 360 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /media/yocto/Olinuxino/poky/meta-sunxi/recipes-kernel/linux/linux-sunxi_3.4.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by icapa** [comment]
After some testing, I changed to gcc-7.3 instead of 8 version and I solved this problem. Now the kernel is compiled correctly but the recipe fails trying to make "sun7i-a20-olinuxino-micro.dtb".
------------
ERROR: Function failed: do_compile (log file is located at /media/yocto/Olinuxino/poky/build_7_3/tmp/work/olinuxino_a20-poky-linux-gnueabi/linux-sunxi/3.4.104-r1/temp/log.do_compile.13881)
-----------
It suppose that in kernel 3.4 this "dtb" file is not mandatory, I tried to modified the recipe to avoid this but It didn't work, I don't know exactly what file I should modify, I understand the problem is here:
--------------
do_compile() {
        for dtbf in sun7i-a20-olinuxino-micro.dtb; do
                dtb=`normalize_dtb "$dtbf"`
                oe_runmake $dtb
        done
}
---------------
But I don't know how to proceed, any idea please?
Thanks in advance

**Comment by slapin** [comment]
I guess 3.4 doesn't support olinuxino-micro which makes sense.
If you don't need support for that board just add check that dtb file
exists.
Otherwise use later kernel version.

**Comment by nandra** [comment]
Fixed. Closing.
