### ISSUE TITLE
Dri2proto has been replaced with xorgproto

### ISSUE THREAD

**Issue by medemi68** [linux-sunxi/meta-sunxi#242]
Hello Everyone,

I just thought I would mention that dri2proto has been replaced by xorgproto as of Yocto 2.6 (thud):
https://wiki.yoctoproject.org/wiki/FutureMigrationGuide

This causes the familiar `Nothing PROVIDES 'dri2proto'`, and it also causes the same issue with xextproto in `/recipes-graphics/xorg-xserver/libdri2_git.bb`

Any chance we can remove xextproto and dri2proto everywhere it is mentioned for dependencies and change it to xorgproto?

**Comment by nandra** [comment]
Added PR#252

**Comment by nandra** [comment]
Merged to master, thus closing.
