### ISSUE TITLE
Missing LAYERDEPENDS in layer.conf

### ISSUE THREAD

**Issue by macpijan** [linux-sunxi/meta-sunxi#254]
https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#var-LAYERDEPENDS

It would be nice to use it, so at parse time user knows whether he has all the layers this layer depends on. I'm sure it depends on core and meta-openembedded/meta-oe.
I'm going to inspect if anything else and submit a PR.

**Comment by nandra** [comment]
:+1: yes please PR welcome ;)
