### ISSUE TITLE
Add example wic file

### ISSUE THREAD

**Issue by macpijan** [linux-sunxi/meta-sunxi#255]
wic support is in Yocto for a few years already I guess. The WKS file is much easier to read and maintain. I have a few examples here and there. Will post something which does more or less the same as the class: https://github.com/linux-sunxi/meta-sunxi/blob/master/classes/sdcard_image-sunxi.bbclass

**Comment by nandra** [comment]
Perfect. Thanks :+1:

**Comment by slapin** [comment]
Links to docs to people with broken google are welcome.

**Comment by nandra** [comment]
@macpijan any update on this? Thanks.
