### ISSUE TITLE
where do we keep firmware files for touchscreens?

### ISSUE THREAD

**Issue by slapin** [linux-sunxi/meta-sunxi#267]
There are machine-specific touchscreen firmware files for popular Silead touchscreens. They are extracted from vendor device drivers. Where these are generally stored so recipes could pick them up? I made touch on my tablet work (generic nameless a13-mid), it would be not nice if I can't share.

**Comment by nandra** [comment]
We have firmware for wifi in repo: https://github.com/linux-sunxi/meta-sunxi/tree/master/recipes-kernel/xradio-firmware so maybe we should move it to sunxi-firmware or so directory and put everything in.

**Comment by slapin** [comment]
there is gsl-firmware repo in github, but I do not know how well it is
maintained, will try to contact there, but will initially add to
linux-sunxi repo.

**Comment by nandra** [comment]
@slapin any update on this?

**Comment by slapin** [comment]
Not yet as I got very well into actual touch working as I was not able to
fix offset problem.

**Comment by nandra** [comment]
@slapin ping? Can we close this or?

**Comment by slapin** [comment]
Hi,
Sorry, life took its toll. Feel free to decide on this for now, but I guess
some final decision should be commented on here
(I still have the stuff and it works more or less fine, would be nice to
finally put it where it belongs).

Thanks!

**Comment by nandra** [comment]
@slapin maybe try to push your changes and we can discuss in pull request ;). Thanks.
