### ISSUE TITLE
support mali r9p0

### ISSUE THREAD

**Issue by smzahraee** [linux-sunxi/meta-sunxi#269]
is it possible to support newest mali blob with [mripard repository]( https://github.com/mripard/sunxi-mali) repository

**Comment by nandra** [comment]
Hi @smzahraee . I have experimental branch with this located here: https://github.com/nandra/meta-sunxi/commits/mbe-gles-mali It's not yes pushed to meta-sunxi as I didn't verify if it works with opengl. Help welcomed ;)

**Comment by smzahraee** [comment]
Hi thanks 
do you test lima on mainline kernel? 
is it comparable with mali blobs?

**Comment by nandra** [comment]
Hi not yet but I have plan to do it. If I have something I'll share it here. Thanks.

**Comment by nandra** [comment]
@smzahraee did you try my branch? Does it work for your needs? Thanks.

**Comment by nandra** [comment]
I'm in process now to take this recipe ```https://layers.openembedded.org/layerindex/recipe/97617/``` and try to poke with configuration and play with latest kernel to check if acceleration works .

**Comment by smzahraee** [comment]
I will test it in following week and inform you, thank you so much

**Comment by nandra** [comment]
@smzahraee ping, any update on this? Thanks.

**Comment by nandra** [comment]
Due inactivity, closing.
