### ISSUE TITLE
Support for Banana-Pi M4 ?

### ISSUE THREAD

**Issue by hsnhrn** [linux-sunxi/meta-sunxi#282]
Can this layer be also used for M4? if not how could we use it for m4?

**Comment by nandra** [comment]
@hsnhrn absolutely. We need to create new machine config and we currently have pretty recent kernel version so I suppose it should work. Pull requests are welcomed ;). If you need hand just say. :+1:

**Comment by hsnhrn** [comment]
Thanks for a quick reply. let me try :D

**Comment by hsnhrn** [comment]
MACHINE ??= "raspberrypi"
what should i put here?

**Comment by nandra** [comment]
Well first you need to create machine configuration (look at [https://github.com/linux-sunxi/meta-sunxi/tree/master/conf/machine](machines) for inspiration)

**Comment by hsnhrn** [comment]
require conf/machine/include/sun7i.inc

KERNEL_DEVICETREE = "sun7i-a20-bananapi.dtb"
UBOOT_MACHINE = "Bananapi_config"
SUNXI_FEX_FILE = "sys_config/a20/Bananapi.fex"

Thats what there for bananapi a20.. I dont have much knowledge about low level kernel development. :(

**Comment by hsnhrn** [comment]
Is it possible for you to help?

**Comment by nandra** [comment]
Sure but seems like this board doesn't have allwinner CPU (I overlooked it). So it doesn't fit unfortunately this meta-sunxi which have support for allwinner CPU arch. Thanks.
