### ISSUE TITLE
USB not working on Cubietruck (missing AXP20x driver)

### ISSUE THREAD

**Issue by Simpson474** [linux-sunxi/meta-sunxi#305]
The issue seems to be exactly the same as #275. The Cubietruck is also using the AXP20x PMIC, but the required driver is missing. After adding the following line to the file "linux-mainline.inc", the USB ports are working:
`SRC_URI_append_cubietruck = " file://axp20x.cfg"`

**Comment by nandra** [comment]
@Simpson474 can you pls post a patch with this fix so it can be merged? Thanks.

**Comment by Simpson474** [comment]
Please find attached the patch containing the newly added line:
[cubietruck.zip](https://github.com/linux-sunxi/meta-sunxi/files/5724128/cubietruck.zip)

**Comment by nandra** [comment]
OK thanks. Pushed to master. If you need it to some other branch pls let me know.
