### ISSUE TITLE
Support for Horister?

### ISSUE THREAD

**Issue by lordfolken** [linux-sunxi/meta-sunxi#332]
Hello, 

https://www.yoctoproject.org/software-overview/downloads/ seems to offer horister 3.4. But so far i see no sunxi support for it. Am I correct?

**Comment by nandra** [comment]
Hi @lordfolken  if you clone recent master it is compatible with honister ;). I'll create separate branch also. Thanks.

**Comment by lordfolken** [comment]
Ah, i see now the honister branch. Thank you. The openvario project will send a few more cubie boards flying. (gracefully) ;) https://www.youtube.com/watch?v=lWnkxg1zPAk
