### ISSUE TITLE
Random boot stuck

### ISSUE THREAD

**Issue by matteolel** [linux-sunxi/meta-sunxi#354]
Hi,

I'm trying to using this layer for a Banana Pi M2 Zero (I will add a pull request later for a new machine).
I was able to boot, but sometimes (at least 1 out of 2/3 reboots) the boot stuck waiting for MMC. Here last prints on debug serial:

```
[    1.255126] hub 3-0:1.0: USB hub found
[    1.258932] mmc1: host does not support reading read-only switch, assuming write-enable
[    1.267004] hub 3-0:1.0: 1 port detected
[    1.271373] mmc1: new high speed SDHC card at address b368
[    1.276475] mmc0: new high speed SDIO card at address 0001
[    1.278813] mmcblk1: mmc1:b368 NCard 29.1 GiB 
[    1.320411]  mmcblk1: p1 p2
[    1.324131] Waiting for root device /dev/mmcblk0p2...
[    1.739841] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    1.941350] hub 1-1:1.0: USB hub found
[    1.945262] hub 1-1:1.0: 4 ports detected
[   31.839842] vcc3v0: disabling
```

After looking in some forums, there are several other people with the same problem, but without a convincing solution.
Then, I tried to change SD card, power supply, and ditributions. I always had the problem, except for armbian!
I looked in every patch made in armbian and I found [that one](https://github.com/armbian/build/blob/master/patch/kernel/archive/sunxi-5.15/megous/arm64-dts-allwinner-Enforce-consistent-MMC-numbering.patch).
Looking debug prints when the device boot, I saw that the mmc devices have a different number!!

```
[    1.252270] hub 3-0:1.0: USB hub found
[    1.256098] hub 3-0:1.0: 1 port detected
[    1.262507] Waiting for root device /dev/mmcblk0p2...
[    1.266753] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.277659] mmc0: new high speed SDHC card at address b368
[    1.284165] mmcblk0: mmc0:b368 NCard 29.1 GiB 
[    1.291102]  mmcblk0: p1 p2
[    1.340657] random: fast init done
[    1.386531] mmc1: new high speed SDIO card at address 0001
[    1.445194] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null). Quota mode: disabled.
[    1.455514] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.463675] devtmpfs: mounted
[    1.468077] Freeing unused kernel image (initmem) memory: 1024K
[    1.474245] Run /sbin/init as init process
```

After adding some aliases in the DTS, I finally fix the problem!
Now I'm able to boot at every startup.

**Comment by ebutera** [comment]
yes, without the patch the microsd mmc (sdio) can be enumerated after the wifi sdio so the root device will not match.
Looks good to me
