### ISSUE TITLE
[OrangePi PC2] Wrong place for dtb in boot partition

### ISSUE THREAD

**Issue by javad123javad** [linux-sunxi/meta-sunxi#399]
Hi,
I've made a minimal image from master branch. After burning the `wic` image on the sdcard, The device tree file is located in <boot partition> while the u-boot is trying to load it from `allwiner/<device tree>.dtb` . How should I solve this problem? 
```
Found U-Boot script /boot.scr
537 bytes read in 3 ms (174.8 KiB/s)
## Executing script at 4fc00000
Failed to load 'allwinner/sun50i-h5-orangepi-pc2.dtb'

```

**Comment by nandra** [comment]
@javad123javad which commit did you use from master please? I've pushed recently fix for this issue. Thanks.

**Comment by javad123javad** [comment]
> @javad123javad which commit did you use from master please? I've pushed recently fix for this issue. Thanks.

Thanks, `git pull` solved the problem. My repo was old.

**Comment by nandra** [comment]
:+1:
