### ISSUE TITLE
How to control the red/green LEDs on Orange Pi Zero LTS with the latest master (Styhead) meta-sunxi?

### ISSUE THREAD

**Issue by ChristianReese** [linux-sunxi/meta-sunxi#423]
I'm no longer seeing the file directories needed to control the red LED - before we had been writing to `/sys/devices/platform/leds/leds/orangepi:red:status/brightness`, but it seems that file no longer exists (since we updated from Hardknott to Mickledore). I have since updated to Styhead (master), but it still isn't there. Did the file directory change, or is this a new bug?

**Comment by nandra** [comment]
GPIO_SYSFS is deprecated from some kernel version (see: https://www.thegoodpenguin.co.uk/blog/stop-using-sys-class-gpio-its-deprecated/). You can still enable it in kernel config but I would suggest to switch to `gpiod`
