### ISSUE TITLE
How to get cubietruck with Qt5

### ISSUE THREAD

**Issue by diegosueiro** [linux-sunxi/meta-sunxi#62]
Folks,

I'm trying to get cubietruck and qt5 with mali support.

Basically we have to scenarios:
- X11 with mali accelerated 
- Framebuffer with mali accelerated

I couldn't get none of these working. Both tells me error with EGL.

Anyone ever get cubietruck with qt5 and accelerated HW?

**Comment by ZARk-be** [comment]
did you manage solving this ?

**Comment by diegosueiro** [comment]
Yes,

In daisy branch a have to use this kernel:
git://github.com/ssvb/linux-sunxi.git;branch=20140116-mali-r3p2-01rel2;

On sunxi-mali recipe this configure step:
do_configure() {
             DESTDIR=${D}/ VERSION=r3p2-01rel1 ABI=armhf ${EXTRA_OECONF} make config
}

And on qtbase include this patch:
--- qtbase-opensource-src-5.2.1.orig/src/plugins/platforms/eglfs/qeglfshooks_stub.cpp	2014-02-01 18:37:36.000000000 -0200
+++ qtbase-opensource-src-5.2.1/src/plugins/platforms/eglfs/qeglfshooks_stub.cpp	2014-05-15 17:04:19.117306579 -0300
@@ -251,7 +251,12 @@
     Q_UNUSED(platformWindow);
     Q_UNUSED(size);
     Q_UNUSED(format);
-    return 0;
+//    return 0;
+	static struct mali_native_window native_window = {
+        .width = (short unsigned int)size.width(),
+        .height = (short unsigned int)size.height(),
+    };
+    return &native_window;
 }
 
 void QEglFSHooks::destroyNativeWindow(EGLNativeWindowType window)

**Comment by nandra** [comment]
@diegosueiro can you pls try on latest thud branch if issue is resolved? Thanks.

**Comment by diegosueiro** [comment]
@nandra,

Unfortunately, I'm not able to test since I don't have the board anymore.

**Comment by nandra** [comment]
OK thanks for info. I'm working on adding proper mali support (mainline kernel + blobs) so will try then on my board and it should work also on others ;). Thanks.
