### ISSUE TITLE
Socarch definition missing?

### ISSUE THREAD

**Issue by jlucius** [linux-sunxi/meta-sunxi#94]
In sunxi.inc the following definition is done:
# Sub-architecture support

MACHINE_SOCARCH_SUFFIX ?= ""
MACHINE_SOCARCH_SUFFIX_sun4i = "-sun4i"

does it not need to define the other sufixes as well?

e.g.
MACHINE_SOCARCH_SUFFIX_sun5i = "-sun5i"
MACHINE_SOCARCH_SUFFIX_sun7i = "-sun7i"

?

**Comment by Noxenious** [comment]
and another issue: it includes

include conf/machine/include/soc-family.inc

but where is this file?

**Comment by naguirre** [comment]
soc-family.inc is included from here : https://github.com/openembedded/oe-core/blob/master/meta/conf/machine/include/soc-family.inc

About the subarch support, i need to check.

**Comment by Noxenious** [comment]
Should it not be included in the meta-sunxi layer? Otherwise it depens on meta-oe (was the same case for linux.inc in kernel)

**Comment by naguirre** [comment]
No, it depends on oe-core, which is the default one.
linux.inc is included in meta-oe wich is a different layer.
